---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
"WHAT'S this?" I pondered. "Have I slept?   
Or can I have been drinking?"   
But soon a gentler feeling crept   
Upon me, and I sat and wept   
An hour or so, like winking.   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
The three stood listening to a fresh access  
Of wind that caught against the house a moment,  
Gulped snow, and then blew free again-the Coles  
Dressed, but dishevelled from some hours of sleep,  
Meserve belittled in the great skin coat he wore.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Listen my children and you shall hear  
Of the midnight ride of Paul Revere,  
On the eighteenth of April, in Seventy-five;  
Hardly a man is now alive  
Who remembers that famous day and year.  

He said to his friend, "If the British march  
By land or sea from the town to-night,  
Hang a lantern aloft in the belfry arch  
Of the North Church tower as a signal light,--  
One if by land, and two if by sea;  
And I on the opposite shore will be,  
Ready to ride and spread the alarm  
Through every Middlesex village and farm,  
For the country folk to be up and to arm."  